from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 801, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.new_contact = QtWidgets.QWidget()
        self.new_contact.setObjectName("new_contact")
        self.formLayoutWidget = QtWidgets.QWidget(self.new_contact)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 471))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.callsignEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.callsignEdit.setObjectName("callsignEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.callsignEdit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.nameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.locationEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.locationEdit.setObjectName("locationEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.locationEdit)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.stationTypeCombo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.stationTypeCombo.setObjectName("stationTypeCombo")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.stationTypeCombo.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stationTypeCombo)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.signalReportEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.signalReportEdit.setObjectName("signalReportEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.signalReportEdit)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.label_7)
        self.commentsEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.commentsEdit.setObjectName("commentsEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.commentsEdit)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.frequencyEdit = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.frequencyEdit.setDecimals(3)
        self.frequencyEdit.setMaximum(999.0)
        self.frequencyEdit.setObjectName("frequencyEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.frequencyEdit)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.unitCombo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.unitCombo.setObjectName("unitCombo")
        self.unitCombo.addItem("")
        self.unitCombo.addItem("")
        self.unitCombo.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.unitCombo)
        self.clear_form = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clear_form.setFont(font)
        self.clear_form.setObjectName("clear_form")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.clear_form)
        self.log_contact = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.log_contact.setFont(font)
        self.log_contact.setObjectName("log_contact")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.log_contact)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.bandCombo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.bandCombo.setObjectName("bandCombo")
        self.bandCombo.addItem("")
        self.bandCombo.addItem("")
        self.bandCombo.addItem("")
        self.bandCombo.addItem("")
        self.bandCombo.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.bandCombo)
        self.tabWidget.addTab(self.new_contact, "")
        self.view_contacts = QtWidgets.QWidget()
        self.view_contacts.setObjectName("view_contacts")
        self.contact_table = QtWidgets.QTableView(self.view_contacts)
        self.contact_table.setGeometry(QtCore.QRect(10, 10, 781, 471))
        self.contact_table.setObjectName("contact_table")
        self.tabWidget.addTab(self.view_contacts, "")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(26, 530, 171, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(590, 530, 211, 16))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 22))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuLogbook = QtWidgets.QMenu(self.menubar)
        self.menuLogbook.setObjectName("menuLogbook")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStation_Information = QtWidgets.QAction(MainWindow)
        self.actionStation_Information.setObjectName("actionStation_Information")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExport_as_CSV = QtWidgets.QAction(MainWindow)
        self.actionExport_as_CSV.setObjectName("actionExport_as_CSV")
        self.actionErase_All_Logs = QtWidgets.QAction(MainWindow)
        self.actionErase_All_Logs.setObjectName("actionErase_All_Logs")
        self.menuHome.addAction(self.actionStation_Information)
        self.menuHome.addSeparator()
        self.menuHome.addAction(self.actionExit)
        self.menuLogbook.addAction(self.actionExport_as_CSV)
        self.menuLogbook.addSeparator()
        self.menuLogbook.addAction(self.actionErase_All_Logs)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuLogbook.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Date / TIme"))
        self.label_3.setText(_translate("MainWindow", "Callsign"))
        self.label_4.setText(_translate("MainWindow", "Full Name"))
        self.label_5.setText(_translate("MainWindow", "Location"))
        self.label_6.setText(_translate("MainWindow", "Station Type"))
        self.stationTypeCombo.setItemText(0, _translate("MainWindow", "Base Station (Home)"))
        self.stationTypeCombo.setItemText(1, _translate("MainWindow", "Base Station (Away)"))
        self.stationTypeCombo.setItemText(2, _translate("MainWindow", "Base Station (Event)"))
        self.stationTypeCombo.setItemText(3, _translate("MainWindow", "Base Station"))
        self.stationTypeCombo.setItemText(4, _translate("MainWindow", "Mobile (Car)"))
        self.stationTypeCombo.setItemText(5, _translate("MainWindow", "Mobile (Truck)"))
        self.stationTypeCombo.setItemText(6, _translate("MainWindow", "Mobile (Boat)"))
        self.stationTypeCombo.setItemText(7, _translate("MainWindow", "Mobile (Aircraft)"))
        self.stationTypeCombo.setItemText(8, _translate("MainWindow", "Mobile (Handheld)"))
        self.stationTypeCombo.setItemText(9, _translate("MainWindow", "Mobile"))
        self.label_2.setText(_translate("MainWindow", "Signal Report"))
        self.label_7.setText(_translate("MainWindow", "Comments / Notes"))
        self.label_8.setText(_translate("MainWindow", "Frequency"))
        self.label_9.setText(_translate("MainWindow", "Unit"))
        self.unitCombo.setItemText(0, _translate("MainWindow", "kHz"))
        self.unitCombo.setItemText(1, _translate("MainWindow", "gHz"))
        self.unitCombo.setItemText(2, _translate("MainWindow", "Mhz"))
        self.clear_form.setText(_translate("MainWindow", "Clear Form"))
        self.log_contact.setText(_translate("MainWindow", "Log Contact"))
        self.label_10.setText(_translate("MainWindow", "Band"))
        self.bandCombo.setItemText(0, _translate("MainWindow", "MF"))
        self.bandCombo.setItemText(1, _translate("MainWindow", "HF"))
        self.bandCombo.setItemText(2, _translate("MainWindow", "VHF"))
        self.bandCombo.setItemText(3, _translate("MainWindow", "UHF"))
        self.bandCombo.setItemText(4, _translate("MainWindow", "SHF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.new_contact), _translate("MainWindow", "New Contact"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.view_contacts), _translate("MainWindow", "View Contacts"))
        self.label_11.setText(_translate("MainWindow", "Developed by Tamatu Systems NZ"))
        self.label_12.setText(_translate("MainWindow", "Email hamlog@tamasystems.nz for Support"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuLogbook.setTitle(_translate("MainWindow", "Logbook"))
        self.actionStation_Information.setText(_translate("MainWindow", "My Station"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExport_as_CSV.setText(_translate("MainWindow", "Export as CSV"))
        self.actionErase_All_Logs.setText(_translate("MainWindow", "Erase All Logs"))
